language: julia
os:
  - linux
  - osx
julia:
  - 0.5
  - 0.6
  - nightly
notifications:
  email: false
after_success:
  - julia -e 'Pkg.add("Coverage"); cd(Pkg.dir("FunctionZeros")); using Coverage; Coveralls.submit(process_folder()); Codecov.submit(process_folder())'
