name = "FunctionZeros"
uuid = "b21f74c0-b399-568f-9643-d20f4fa2c814"
authors = ["John Lapeyre <jlapeyre@users.noreply.github.com>"]
version = "0.2.3"

[deps]
Roots = "f2b01f46-fcfa-551c-844a-d8ac1e96c665"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"

[compat]
Roots = "0.8, 1.0"
SpecialFunctions = "0.8, 0.9, 0.10, 1.0, 1.1, 1.2, 1.3"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
